export const SECURITY_CONSTANTS = {
  HIGH_ENTROPY_THRESHOLD: 4.5,
  MEDIUM_ENTROPY_THRESHOLD: 3.5,
  GIT_HISTORY_COMMIT_LIMIT: 100,
  GIT_HISTORY_DIFF_MAX_BYTES: 32 * 1024 * 1024,
  CODE_SNIPPET_CONTEXT_LINES: 3,
  SECRET_MASK_PREFIX_LENGTH: 4,
  SECRET_MASK_SUFFIX_LENGTH: 4,
} as const;
