-- GuardScan Core Schema - Open Source Edition
-- Migration: 001_core_schema
-- Description: Core telemetry tables for privacy-preserving usage analytics
-- Created: 2024-11-17

-- ============================================================================
-- CLIENTS TABLE
-- ============================================================================
-- Tracks unique CLI installations (no payment or PII data)
CREATE TABLE IF NOT EXISTS clients (
    client_id TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ,
    cli_version TEXT,
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Indexes for clients table
CREATE INDEX IF NOT EXISTS idx_clients_created_at ON clients(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_clients_last_seen ON clients(last_seen_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_clients_cli_version ON clients(cli_version) WHERE cli_version IS NOT NULL;

-- Comments
COMMENT ON TABLE clients IS 'Open-source: Tracks unique CLI installations (no PII, no payment data)';
COMMENT ON COLUMN clients.client_id IS 'Unique client identifier (UUID generated by CLI on init)';
COMMENT ON COLUMN clients.created_at IS 'First time CLI was initialized';
COMMENT ON COLUMN clients.last_seen_at IS 'Last activity timestamp (updated on telemetry sync)';
COMMENT ON COLUMN clients.cli_version IS 'GuardScan CLI version string (e.g., "1.0.0")';
COMMENT ON COLUMN clients.metadata IS 'Optional extensible metadata (JSONB)';

-- ============================================================================
-- TELEMETRY TABLE
-- ============================================================================
-- Stores anonymized usage telemetry (privacy-preserving)
CREATE TABLE IF NOT EXISTS telemetry (
    event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id TEXT NOT NULL REFERENCES clients(client_id) ON DELETE CASCADE,
    repo_id TEXT NOT NULL,
    action_type TEXT NOT NULL,
    duration_ms INTEGER,
    model TEXT,
    loc INTEGER,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb,
    
    -- Constraints
    CONSTRAINT valid_action_type CHECK (action_type IN (
        'scan', 'review', 'test-gen', 'security', 'sbom', 'perf',
        'mutation', 'rules', 'config', 'status', 'reset', 'init',
        'run', 'commit', 'chat', 'explain', 'refactor', 'docs',
        'threat-model', 'migrate'
    )),
    CONSTRAINT positive_duration CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT positive_loc CHECK (loc IS NULL OR loc >= 0)
);

-- Indexes for telemetry table
CREATE INDEX IF NOT EXISTS idx_telemetry_client_id ON telemetry(client_id);
CREATE INDEX IF NOT EXISTS idx_telemetry_repo_id ON telemetry(repo_id);
CREATE INDEX IF NOT EXISTS idx_telemetry_action_type ON telemetry(action_type);
CREATE INDEX IF NOT EXISTS idx_telemetry_timestamp ON telemetry(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_model ON telemetry(model) WHERE model IS NOT NULL;

-- Composite indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_telemetry_client_action_time ON telemetry(client_id, action_type, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_action_time ON telemetry(action_type, timestamp DESC);

-- Comments
COMMENT ON TABLE telemetry IS 'Privacy-preserving usage analytics (NO source code, NO file paths, opt-out available)';
COMMENT ON COLUMN telemetry.event_id IS 'Unique event identifier (auto-generated UUID)';
COMMENT ON COLUMN telemetry.client_id IS 'References clients table (tracks which CLI instance)';
COMMENT ON COLUMN telemetry.repo_id IS 'Anonymized repository identifier (cryptographic hash of git remote)';
COMMENT ON COLUMN telemetry.action_type IS 'CLI command executed (e.g., scan, review, test-gen)';
COMMENT ON COLUMN telemetry.duration_ms IS 'Command execution duration in milliseconds';
COMMENT ON COLUMN telemetry.model IS 'AI model used for this action (e.g., gpt-4, claude-3)';
COMMENT ON COLUMN telemetry.loc IS 'Lines of code processed in this action';
COMMENT ON COLUMN telemetry.timestamp IS 'Event timestamp (when command was executed)';
COMMENT ON COLUMN telemetry.metadata IS 'Additional event metadata (extensible JSONB)';

-- ============================================================================
-- INITIAL DATA
-- ============================================================================

-- System account for internal operations
INSERT INTO clients (client_id, cli_version, metadata)
VALUES (
    'system',
    '1.0.0',
    '{"is_system": true, "description": "System account for internal operations"}'
)
ON CONFLICT (client_id) DO NOTHING;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Display summary
DO $$
BEGIN
    RAISE NOTICE '==========================================';
    RAISE NOTICE 'GuardScan Core Schema Applied';
    RAISE NOTICE '==========================================';
    RAISE NOTICE 'Tables created: clients, telemetry';
    RAISE NOTICE 'Total clients: %', (SELECT COUNT(*) FROM clients);
    RAISE NOTICE 'Total telemetry events: %', (SELECT COUNT(*) FROM telemetry);
    RAISE NOTICE '==========================================';
END $$;

